/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supermarket.managment;

import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author My PC
 */
public class billingpoint extends javax.swing.JFrame {

    
    public billingpoint() {
        initComponents();
        Selectproduct();
        getcatgories();
    }
    Connection con=null;
    Statement stmt=null;
    ResultSet rs=null;
    
    
    int pid,newqty=0;
    
public void updateqty()
{
       String pname = pname_field.getText();
       String qty = qty_field.getText();
       newqty=AvaliableQty-Integer.valueOf(qty_field.getText());
       String updateQuery = "UPDATE AWAIS.MANAGEPRODUCT SET " +
        "pqty = " + newqty + " " + // Updated pqty with newqty
        "WHERE PID = " + pid;
       
        try {
            con=DriverManager.getConnection("jdbc:derby://localhost:1527/SuperMarket","awais","awais");     
          stmt=con.createStatement();
        stmt.executeUpdate(updateQuery);
        Selectproduct();
        } catch (Exception e) {
            
            e.printStackTrace();
        }
    }
 private void Selectproduct(){
    try {
            con=DriverManager.getConnection("jdbc:derby://localhost:1527/SuperMarket","awais","awais");
            stmt=con.createStatement();
            rs=stmt.executeQuery("Select * from AWAIS.MANAGEPRODUCT");
            billprodtable.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch(SQLException ex) {
            Logger.getLogger(Seller_Account.class.getName()).log(Level.SEVERE, null, ex);
        }
   }
 private void ClearAll(){
      Bill_id.setText("");
       pname_field.setText("");
       qty_field.setText("");
       prodtype_combo.setSelectedItem("");
}
 
 private void getcatgories(){
     try {
            con=DriverManager.getConnection("jdbc:derby://localhost:1527/SuperMarket","awais","awais");
            stmt=con.createStatement();
            rs=stmt.executeQuery("Select * from AWAIS.CATEGORYTABLE");
            while(rs.next()){
                String cat=rs.getString("CATNAME");
                prodtype_combo.addItem(cat);
            }
            
        } catch(SQLException ex) {
            Logger.getLogger(Seller_Account.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Bill_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        pname_field = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        qty_field = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        prodtype_combo = new javax.swing.JComboBox<String>();
        addbtn = new javax.swing.JButton();
        refreshbtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        billprodtable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        billtxt = new javax.swing.JTextPane();
        printbtn = new javax.swing.JButton();
        gdtotaltxt = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        selleracc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(242, 231, 192));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(255, 102, 102));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 102));
        jLabel3.setText("Product List");

        Bill_id.setForeground(new java.awt.Color(255, 51, 102));
        Bill_id.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Bill_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bill_idActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 102, 102));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 102));
        jLabel1.setText("Bill ID:");

        pname_field.setForeground(new java.awt.Color(255, 51, 102));
        pname_field.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pname_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pname_fieldActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 102, 102));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 102));
        jLabel2.setText("Quantity:");

        qty_field.setForeground(new java.awt.Color(255, 51, 102));
        qty_field.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        qty_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qty_fieldActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 102, 102));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 102));
        jLabel4.setText("Product Name:");

        prodtype_combo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        prodtype_combo.setForeground(new java.awt.Color(255, 51, 102));
        prodtype_combo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prodtype_comboMouseClicked(evt);
            }
        });

        addbtn.setBackground(new java.awt.Color(242, 231, 192));
        addbtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        addbtn.setForeground(new java.awt.Color(255, 51, 102));
        addbtn.setText("ADD TO LIST");
        addbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addbtnMouseClicked(evt);
            }
        });
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        refreshbtn.setBackground(new java.awt.Color(242, 231, 192));
        refreshbtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        refreshbtn.setForeground(new java.awt.Color(255, 51, 102));
        refreshbtn.setText("Refresh");
        refreshbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshbtnMouseClicked(evt);
            }
        });
        refreshbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshbtnActionPerformed(evt);
            }
        });

        clearbtn.setBackground(new java.awt.Color(242, 231, 192));
        clearbtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        clearbtn.setForeground(new java.awt.Color(255, 51, 102));
        clearbtn.setText("CLEAR");
        clearbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearbtnMouseClicked(evt);
            }
        });
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });

        billprodtable.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        billprodtable.setForeground(new java.awt.Color(255, 51, 102));
        billprodtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Product ID", "Product Name", "Price ", "Quantity", "Category"
            }
        ));
        billprodtable.setRowHeight(20);
        billprodtable.setSelectionBackground(new java.awt.Color(242, 231, 192));
        billprodtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billprodtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(billprodtable);

        jLabel7.setBackground(new java.awt.Color(255, 102, 102));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 102));
        jLabel7.setText("Billing Point");

        jLabel6.setBackground(new java.awt.Color(255, 102, 102));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 102));
        jLabel6.setText("Filter By:");

        jScrollPane2.setViewportView(billtxt);

        printbtn.setBackground(new java.awt.Color(242, 231, 192));
        printbtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        printbtn.setForeground(new java.awt.Color(255, 51, 102));
        printbtn.setText("Print Bill");
        printbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printbtnMouseClicked(evt);
            }
        });
        printbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printbtnActionPerformed(evt);
            }
        });

        gdtotaltxt.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        gdtotaltxt.setForeground(new java.awt.Color(255, 51, 102));
        gdtotaltxt.setText("RS: 0.0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(366, 366, 366)
                .addComponent(jLabel7)
                .addGap(223, 223, 223)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pname_field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Bill_id, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(qty_field, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(200, 200, 200)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(251, 251, 251)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(prodtype_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(refreshbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139)
                        .addComponent(clearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(194, 194, 194)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(554, 554, 554))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(printbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gdtotaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(727, 727, 727))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel3)))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel6)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(prodtype_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(refreshbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Bill_id, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pname_field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(qty_field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(40, 40, 40))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(gdtotaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(printbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(203, 203, 203))
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supermarket/managment/placeholder (1).png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 102));
        jLabel9.setText("Value Mart");

        selleracc.setBackground(new java.awt.Color(255, 255, 255));
        selleracc.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        selleracc.setForeground(new java.awt.Color(255, 51, 102));
        selleracc.setText("Logout");
        selleracc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 0, true));
        selleracc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selleraccMouseClicked(evt);
            }
        });
        selleracc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selleraccActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(selleracc, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1247, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(selleracc, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(218, 218, 218))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bill_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bill_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bill_idActionPerformed

    private void pname_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pname_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pname_fieldActionPerformed

    private void qty_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qty_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qty_fieldActionPerformed
   int i=0;
   Double Total=0.0,Grandtotal=0.0;
  Double Unitprice=0.0;
  int AvaliableQty;
  int Billid=0;
  
    private void addbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbtnMouseClicked
    
        
       if(pname_field.getText().isEmpty()||qty_field.getText().toString().isEmpty()){
            JOptionPane.showMessageDialog(this,"Kindly Enter Missing Value...");
        }
       else if(AvaliableQty<=Integer.valueOf(qty_field.getText())){
        JOptionPane.showMessageDialog(this, "Not Enough Quantity ! Sorry for inconvinence");
    }
        else{
          i++;
          Total=Unitprice * Double.valueOf(qty_field.getText());
          Grandtotal+=Total;
          if(i==1)
          {
              Billid++;
             Bill_id.setText(String.valueOf(Billid));    
                  billtxt.setText(billtxt.getText() + "\t Welcome to SuperMarket\n\t************YOUR BILL*************\n" + " NUM    \tNAME    \tPRICE    \tQUANTITY    \tTOTAL\n " + " " + i + "      \t" + pname_field.getText() + "\t" +
                  Unitprice + "\t" + qty_field.getText() + "\t" + Total + "\n");
        }
          else{
            billtxt.setText(billtxt.getText() + "  " + i + "\t" + pname_field.getText() + "\t" + Unitprice + "\t" + qty_field.getText()+ "\t" + Total + "\n");
       
          }
          gdtotaltxt.setText("RS: "+Grandtotal);
          updateqty();
    
       }
    }//GEN-LAST:event_addbtnMouseClicked

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addbtnActionPerformed

    private void refreshbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshbtnMouseClicked

      Selectproduct();
    }//GEN-LAST:event_refreshbtnMouseClicked

    private void refreshbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshbtnActionPerformed

    private void clearbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearbtnMouseClicked

        ClearAll();
    }//GEN-LAST:event_clearbtnMouseClicked

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearbtnActionPerformed

    private void billprodtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billprodtableMouseClicked

        TableModel model=billprodtable.getModel();
        int index=billprodtable.getSelectedRow();
        AvaliableQty=Integer.valueOf(model.getValueAt(index, 3).toString());
        pid=Integer.valueOf(model.getValueAt(index, 0).toString());
        pname_field.setText(model.getValueAt(index, 1).toString());
        Unitprice=Double.valueOf(model.getValueAt(index, 2).toString());
   
    }//GEN-LAST:event_billprodtableMouseClicked

    private void printbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printbtnMouseClicked
        try {
            i=0;
            billtxt.print();
            
        } catch (Exception e) {
        }
        billtxt.setText("");
    }//GEN-LAST:event_printbtnMouseClicked

    private void printbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printbtnActionPerformed

    private void selleraccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selleraccMouseClicked
        new LoginForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_selleraccMouseClicked

    private void selleraccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selleraccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selleraccActionPerformed

    private void prodtype_comboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prodtype_comboMouseClicked
 try {
            con=DriverManager.getConnection("jdbc:derby://localhost:1527/SuperMarket","awais","awais");
            stmt=con.createStatement();
            rs=stmt.executeQuery("Select * from AWAIS.MANAGEPRODUCT where PCATEGORY='"+prodtype_combo.getSelectedItem().toString()+"'");
            billprodtable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch(SQLException ex) {
            Logger.getLogger(Seller_Account.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_prodtype_comboMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(billingpoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(billingpoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(billingpoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(billingpoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new billingpoint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bill_id;
    private javax.swing.JButton addbtn;
    private javax.swing.JTable billprodtable;
    private javax.swing.JTextPane billtxt;
    private javax.swing.JButton clearbtn;
    private javax.swing.JLabel gdtotaltxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField pname_field;
    private javax.swing.JButton printbtn;
    private javax.swing.JComboBox<String> prodtype_combo;
    private javax.swing.JTextField qty_field;
    private javax.swing.JButton refreshbtn;
    private javax.swing.JButton selleracc;
    // End of variables declaration//GEN-END:variables
}
